site_name: Hybrid Conversion
site_url: https://bjbeazley.github.io/hybrid-conversion-docs/
nav:
  - Home: index.md
  - Design: design.md
theme:
  name: material
  logo: assets/check_engine.png
  favicon: assets/check_engine.png
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
