site_name: Hybrid Conversion
site_url: https://bjbeazley.github.io/hybrid-conversion-docs/
nav:
  - Home: index.md
  - System Design: design.md
theme:
  name: material
  logo: assets/check_engine.png
  favicon: assets/check_engine.png
